<style>
td.available > a {background: #82AF6F}
</style>

<?php if ($this->getCustomer()): ?>
    <h2>Запись пациента <?php echo $this->getCustomer()->getName() ?> на <?php echo date('d.m.Y', $this->getOption('period_start')) ?></h2>
<?php endif ?>

<div>
    <?php foreach ($this->getRooms() as $room): ?>
        <div id="room<?php echo $room['room_id'] ?>" style="float:left;width: 250px;"></div>
    <?php endforeach ?>
</div>
<div id="room" style="float:left;width: 250px;"></div>


<div>

<div id="employees" style="float: left;margin: 20px;">
    <div id="datepicker"></div>
    <!--div class="schedule-header" style="overflow:hidden;text-align: center;heigth: 50px;line-height: 50px;width: 300px;font-size: 14px;">
        <a href="" style="float: left;">&larr;&nbsp;<span id="navi-prev-day"></span></a>
        <span id="navi-day"></span>
        <a href="" style="float: right;"><span id="navi-next-day"></span>&nbsp;&rarr;</a>
    </div-->
    <?php foreach ($this->getAvailableRegistrations() as $item): ?>
        <div style="padding: 5px;"><a id="combo<?php echo $item['id'] ?>" href="#"><?php echo $item['title'] ?></a></div>
    <?php endforeach ?>
</div>


</div>

<div id="register-form-container"/>


<script>

    $j(function($) {

        var todayDate = new Date(<?php echo $this->getTodayTimestamp() * 1000 ?>);
        var yesterdayDate = new Date(<?php echo ($this->getTodayTimestamp() - 24 * 60 * 60) * 1000 ?>);
        var tomorrowDate = new Date(<?php echo ($this->getTodayTimestamp() + 24 * 60 * 60) * 1000 ?>);


        $('#navi-prev-day').html($.fullCalendar.formatDate(yesterdayDate, 'dd MMMM')).click(function() {
            $("div[id^='room']").fullCalendar('prev');
            return false;
        });
        $('#navi-day').html($.fullCalendar.formatDate(todayDate, 'dd MMMM'));
        $('#navi-next-day').html($.fullCalendar.formatDate(tomorrowDate, 'dd MMMM')).click(function() {
            $("div[id^='room']").fullCalendar('next');
            console.log(todayDate);
//            todayDate.setDate(todayDate.getDate()+1);
            return false;
        });

        <?php foreach ($this->getRooms() as $room): ?>
            var calendar<?php echo $room['room_id'] ?> = $('#room<?php echo $room['room_id'] ?>').fullCalendar({
                height: 1000,
                minTime: 9,
                maxTime: 19,
                slotMinutes: 15,
                defaultView: 'agendaDay',
                allDaySlot: false,
                axisFormat: 'H:mm',
                header: {left: '', right: '', center: ''},
                columnFormat: {day: '<?php echo $room['name'] ?>'},
                selectable: true,
                selectHelper: true,
                events: <?php echo json_encode($this->getRoomEvents($room['room_id'])) ?>,
                eventClick: function(calEvent, jsEvent, view) {
//                    console.log(calEvent);
//                    console.log(jsEvent);
                    $.get('<?php echo $this->getUrl('*/register_ajax/add') ?>',
                        {schedule_id: calEvent.schedule_id, user_id: calEvent.user_id, customer_id: <?php echo $this->getCustomer()->getId() ?>, start:calEvent.timestamp_start},
                        function(response) {
                            $('#register-form-container').html(response);
                            $("#register-form-container").dialog("open");
                            $('#register-form').submit(function(event) {
                                $(this).ajaxSubmit({'success': function(response) {
                                    calendar<?php echo $room['room_id'] ?>.fullCalendar('renderEvent',
                                        $.parseJSON(response),
                                        true // make the event "stick"
                                    );
                                    $("#register-form-container").dialog("close");
                                }});
                                event.preventDefault();
                        });
                    });

                }
            });
        <?php endforeach ?>


        $('.product-category').click(function() {
            $('.' + this.id + '-product').prop('checked', this.checked);
        });

        var availableDays = <?php echo $this->getAvailableDaysJson() ?>;
        $( "#datepicker" ).datepicker({
            onSelect: function(selectedDate) {
                $("div[id^='room']").fullCalendar('gotoDate', new Date(selectedDate));
            },
            minDate: 0,
            maxDate: "+20D",
            dateFormat: "yy-mm-dd",
            firstDay: 1,
            beforeShowDay: function(d) {
                var dString = $.fullCalendar.formatDate(d, 'yyyy-MM-dd');
                if (availableDays[dString]) {
                    return [true,"available"];
                } else {
                    return [false,""];
                }
            }
        });

        $("#register-form-container").dialog({
            autoOpen: false,
            height: 500,
            width: 500,
            modal: true,
            buttons: [
                {
                    text: "Записать",
                    click: function() {
                        $('#register-form').submit();

                    }
                },
                {
                    text: "Отмена",
                    click: function() {
                        $(this).dialog("close");
                    }
                }
            ]
        });

        <?php foreach ($this->getAvailableRegistrations() as $item): ?>
            $('#combo<?php echo $item['id'] ?>').click(function() {
                <?php foreach ($item['events'] as $roomId => $event): ?>
                    $('#room<?php echo $roomId ?>').fullCalendar('removeEvents', 'temp');
                    $('#room<?php echo $roomId ?>').fullCalendar('renderEvent', <?php echo json_encode($event) ?>, true);
                <?php endforeach ?>
                return false;
            });
        <?php endforeach ?>

    });


</script>
