<style type="text/css">
<!--
#layout {width:900px;font-family:Arial;margin:auto;font-size:100%;color:#333;}
#header {border-bottom:solid 3px #ccc;padding:0 0 15px;margin:0 0 8px;text-align:center;line-height:140%;}
#header img {width:250px;}
#address {float:right;width:225px;text-align:right;padding:30px 0 0;}
#address span {font-size:110%;display:block;}
#contacts {float:left;width:225px;text-align:left;padding:30px 0 0;}
#contacts span {font-size:110%;display:block;}
#license {color:#888;font-size:85%;margin:0 0 35px;}
#content {line-height:160%;font-size:110%;}
#sign {float:right;border-top:solid #ccc 1px;font-size:70%;padding:0 75px;position:relative;top:15px;left:0;z-index:10;}
#copy {color:#888;font-size:70%;padding:25px 0 0;}
-->
</style>

<div id="layout">

<div id="header">
<div id="address"><span>ТОВ «Ревмоцентр»</span>Київ, вул. <b>Спаська, 5</b>, оф. 54<br><small>(вхід з вул. Хорива)</small></div>
<div id="contacts"><span>Попередній запис:</span>(044) <b>537-19-12, 599-33-81</b><br><small>www.ревматология.com.ua</small></div>
<img src="/i/logo-ua.gif">
</div>
<center id="license">Ліцензія МОЗ України Серія АГ №570333 від 29.12.2010 року</center>

<div id="content">
    
<center>
<h2>ВИСНОВОК СПЕЦІАЛІСТА</h2>
<h3><?php echo $this->getEmployee()->getPosition() ?> <?php echo $this->getEmployee()->getName() ?></h3>
</center>

<div style="float:right;">Дата народження: <b><?php echo $this->formatUserDate($this->getCustomer()->getDob()) ?></b></div>
Пацієнт:  <b><?php echo $this->getCustomer()->getName() ?>	</b>

<?php $form = $this->getForm(); ?>
<?php if ($form->getConclusion()): ?>
    <p><b>Висновок:</b></p>
   <i><?php echo $form->getConclusion() ?></i>
<?php endif ?>

<?php if ($form->getRecommendation()): ?>
    <p><b>Рекомендації:</b></p>
    <i><?php echo $form->getRecommendation() ?></i>
<?php endif ?>

<br>
<div id="sign">Підпис</div>
Дата: <b><?php echo $this->formatUserDate($form->getUserDate()) ?></b>

<div id="copy">Документ создан при помощи <b>&laquo;АМЦ Поликлиника&raquo;</b> Версия 0.1</div>

</div>

</div>	


<!-- не нужный код -->
<?php foreach ($form->getFiles() as $file): ?>
    <img src="<?php echo $file['url'] ?>" width="440">
<?php endforeach ?>
