<div id="calendar" style="width:800px;"></div>
<input type="hidden" name="schedule" id="user_schedule" value="">
<script type="text/javascript">
    var schedule = [];

    function jsDateToString(date)
    {
        return $j.fullCalendar.formatDate(date, "yyyy-MM-dd HH:mm:00");
    }

    $j(document).ready(function($) {
        var date = new Date();
        var d = date.getDate();
        var m = date.getMonth();
        var y = date.getFullYear();

        var calendar = $('#calendar').fullCalendar({
            header: {
                left: 'prev,next today',
                center: 'title',
                right: 'month,agendaWeek,agendaDay'
            },
            buttonText: {
                month: 'месяц',
                week: 'неделя',
                day: 'день',
                today: 'сегодня'
            },
            dayNamesShort: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
            monthNames: ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'],
            monthNamesShort: ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'],
            dayNames: ['Воскресенье',     'Понедельник', 'Вторник', 'Среда', 'Четверг','Пятница', 'Суббота'],
            selectable: true,
            selectHelper: true,
            select: function(start, end, allDay) {
                var selected = {title: "", start: start, end: end, allDay: allDay};
                calendar.fullCalendar('renderEvent', selected, true);  // make the event "stick"
                schedule.push({start: jsDateToString(start), end: jsDateToString(end)});
                $('#user_schedule').val(JSON.stringify(schedule));
                calendar.fullCalendar('unselect');
            },
            editable: true,
            events: <?php echo $this->getScheduleJson() ?>,
//            timeFormat: 'HH:mm-HH:mm',
//            axisFormat: 'HH:mm',
            //firstHour: 8,
            minTime: 8,
            maxTime: 19,
            firstDay: 1,
            weekends: false,
            defaultView: 'agendaWeek',
            contentHeight: 600
        });


    });
</script>
